### ISSUE TITLE
Allow customizing of the default theme in theme_picker_ui

### ISSUE THREAD

**Issue by Nelson-Gon** [posit-dev/py-shinyswatch#22]
Hi,

Thanks for this package, it is useful and fun to work with. I was wondering if it could be possible to allow changing of the default theme on startup for example to allow something like `theme_picker_ui(selected = "zephyr")`

I have looked at both the code and function help pages but cannot quite see how this is possible.

Thanks,
Nelson

**Comment by gadenbuie** [comment]
Completed in #32 with follow up in #39
