### ISSUE TITLE
Theme picker causes error

### ISSUE THREAD

**Issue by sebovzeoueb** [posit-dev/py-shinyswatch#35]
I tried to use `shinyswatch.theme_picker_ui()` and `shinyswatch.theme_picker_server()` in my app but I got the following error:

```
File "F:\concierge\Lib\site-packages\starlette\staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'F:\concierge\Lib\site-packages\shinyswatch\picker' does not exist
```
I can confirm that that directory indeed does not exist on my machine

Any idea what could be causing this?

(also, the live demo linked on this repo shows the selector but it doesn't seem to do anything)

**Comment by schloerke** [comment]
I can confirm the demo code is broken.

I believe this is a manifest bug. As local testing works but https://pypi.org/project/shinyswatch/#files does not contain `shinyswatch/picker` folder.

Will fix and do a followup release

**Comment by gadenbuie** [comment]
Hi! Which version of shinyswatch do you have installed? The `picker` folder was introduced in 0.6.0.

Is `F:\concierge\Lib\site-packages\shinyswatch` the location where the shinyswatch package is installed on your machine? Even more specifically, is it the location of the shinyswatch package used in the app where you called `shinyswatch.theme_picker_ui()`? (I suspect the answer is no.)

**Comment by schloerke** [comment]
Thank you @sebovzeoueb !

**Comment by sebovzeoueb** [comment]
Wow, fast fix, thanks, all working perfectly for me now!
