### ISSUE TITLE
theme picker server error stays even after it ends up loading successfully

### ISSUE THREAD

**Issue by sebovzeoueb** [posit-dev/py-shinyswatch#45]
![image](https://github.com/user-attachments/assets/59553e08-4605-455a-83f1-d1d10cbdada0)

In my screenshot you can see that the error is present but the picker is working. I think there was a brief moment during app launch where it was unable to load the picker, but after it started working the error stayed, I would expect it to be cleaned up upon the picker loading successfully.

**Comment by schloerke** [comment]
Absolutely it should go away. 

Is it possible for you to recreate and share your app code that produces the error on shinylive.io? 

This way we can recreate and quickly fix the issue on our end. Thank you!

**Comment by gadenbuie** [comment]
Thanks @sebovzeoueb, and don't worry about creating a repro; I'm happy to see if we can generally improve the situation first and then we can follow up.
